# Generated by Django 3.0.1 on 2020-03-26 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contribution_credit', models.NullBooleanField()),
                ('consent', models.BooleanField()),
                ('jurisdiction', models.CharField(blank=True, help_text='Within Country', max_length=500, null=True)),
                ('court_name', models.CharField(help_text='Original and/or English Translation', max_length=500)),
                ('decision_place', models.CharField(blank=True, max_length=500, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('link_decesion1', models.URLField()),
                ('link_decesion_eng_translated', models.URLField(blank=True, null=True)),
                ('background_info', models.TextField(blank=True, max_length=5000, null=True)),
                ('summary_decesion', models.TextField(blank=True, max_length=5000, null=True)),
                ('result_ruling', models.TextField(blank=True, max_length=5000, null=True)),
                ('implication', models.TextField(blank=True, max_length=5000, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contribution_credit', models.NullBooleanField()),
                ('consent', models.BooleanField()),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField()),
                ('abstract', models.TextField(max_length=5000)),
                ('category', models.ManyToManyField(to='app.Categories')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkScholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='LinkCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='categories',
            field=models.ManyToManyField(to='app.Categories'),
        ),
        migrations.AddField(
            model_name='case',
            name='cc_license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.License'),
        ),
        migrations.AddField(
            model_name='case',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Country'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
