# Generated by Django 3.0.1 on 2020-03-26 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='link_decesion1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='link_decesion_eng_translated',
        ),
        migrations.AddField(
            model_name='case',
            name='file',
            field=models.FileField(null=True, upload_to='case_files'),
        ),
        migrations.AddField(
            model_name='case',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='type',
            field=models.CharField(blank=True, choices=[('POR', 'Ported'), ('GEN', 'GENERIC'), ('INT', 'International')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='version',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='file',
            field=models.FileField(null=True, upload_to='scholarship_files'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='summary',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='cc_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.License'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
